### ISSUE TITLE
Cannot JSON encode object of clas

### ISSUE THREAD

**Issue by greut** [exoscale/raven#22]
```
$ csx updateAccount 
Cloudstack error: HTTP response 500
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class raven.client$resolve_os_name_linux: raven.client$resolve_os_name_linux@d0e6859
        at cheshire.generate$generate.invokeStatic(generate.clj:152)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at cheshire.core$generate_string.invokeStatic(core.clj:74)
        at cheshire.core$generate_string.invoke(core.clj:49)
        at cheshire.core$generate_string.invokeStatic(core.clj:55)
        at cheshire.core$generate_string.invoke(core.clj:49)
        at raven.client$perform_http_request.invokeStatic(client.clj:289)
        at raven.client$perform_http_request.invoke(client.clj:287)
        at raven.client$capture_BANG_.invokeStatic(client.clj:316)
        at raven.client$capture_BANG_.invoke(client.clj:307)
        at spootnik.reporter.Reporter.capture_BANG_(reporter.clj:269)
        at spootnik.reporter.Reporter.capture_BANG_(reporter.clj:266)
        at spootnik.reporter$fn__16793$G__16789__16799.invoke(reporter.clj:34)
        at spootnik.reporter$fn__16793$G__16788__16806.invoke(reporter.clj:34)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at obwald.report$capture_BANG_.invokeStatic(report.clj:28)
        at obwald.report$capture_BANG_.doInvoke(report.clj:28)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at obwald.http$render_exception.invokeStatic(http.clj:42)
        at obwald.http$render_exception.invoke(http.clj:32)
        at obwald.http$make_handler$fn__22181.invoke(http.clj:73)
        at obwald.middleware$wrap_basic_auth$fn__11617.invoke(middleware.clj:24)
        at obwald.middleware$wrap_normalize_keys$fn__11620.invoke(middleware.clj:32)
        at ring.middleware.params$wrap_params$fn__11610.invoke(params.clj:64)
        at obwald.middleware$wrap_params$fn__11623.invoke(middleware.clj:42)
        at aleph.http.server$handle_request$fn__19489$f__675__auto____19490.invoke(server.clj:157)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$3.run(Executor.java:318)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__567$f__568.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by chrisglass** [comment]
That should be fixed in https://github.com/exoscale/raven/commit/7c38254e4d1354973c6e323db1721b2a1277a686 (@pyr)
