### ISSUE TITLE
Cannot JSON

### ISSUE THREAD

**Issue by greut** [exoscale/raven#31]
another error got mangled...

> com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON
        encode object of class: class io.aleph.dirigiste.Executor: io.aleph.dirigiste.Executor@b1308c                                                                           
        at
        cheshire.generate$generate.invokeStatic(generate.clj:152)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at
        cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at
        cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)                                                                                                                  
        at
        cheshire.generate$generate.invokeStatic(generate.clj:122)
        at cheshire.generate$generate.invoke(generate.clj:116)
        at
        cheshire.core$generate_string.invokeStatic(core.clj:74)
        at cheshire.core$generate_string.invoke(core.clj:49)
        at
        cheshire.core$generate_string.invokeStatic(core.clj:55)
        at cheshire.core$generate_string.invoke(core.clj:49)                                                                                                                    
        at
        raven.client$perform_http_request.invokeStatic(client.clj:289)
        at raven.client$perform_http_request.invoke(client.clj:287)
        at
        raven.client$capture_BANG_.invokeStatic(client.clj:316)
        at raven.client$capture_BANG_.invoke(client.clj:307)
        at
        spootnik.reporter.Reporter.capture_BANG_(reporter.clj:269)
        at spootnik.reporter.Reporter.capture_BANG_(reporter.clj:266)
        at
        spootnik.reporter$fn__17038$G__17034__17044.invoke(reporter.clj:34)
        at
        spootnik.reporter$fn__17038$G__17033__17051.invoke(reporter.clj:34)
        at
        clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at
        clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at
        obwald.report$capture_BANG_.invokeStatic(report.clj:28)
        at obwald.report$capture_BANG_.doInvoke(report.clj:28)
        at
        clojure.lang.RestFn.invoke(RestFn.java:408)
        at obwald.http$render_exception.invokeStatic(http.clj:46)

**Comment by greut** [comment]
btw "Cannot JSON" on kibana has quite a bit of them.
